import {
  ArrowLeftRight,
  Banknote,
  BookOpen,
  Brush,
  Calculator,
  CalendarDays,
  CalendarHeart,
  Clapperboard,
  Combine,
  Crop,
  Droplets,
  Eraser,
  FileCode2,
  FileStack,
  FileType,
  Globe,
  Hash,
  HeartPulse,
  Home,
  ImageIcon,
  Layers,
  LayoutGrid,
  ListOrdered,
  Lock,
  Mail,
  MonitorSmartphone,
  Minimize2,
  Music,
  PartyPopper,
  PenLine,
  Percent,
  Printer,
  Pill,
  Presentation,
  QrCode,
  Ruler,
  Scissors,
  ReceiptText,
  Scale,
  ScanText,
  Stamp,
  Tag,
  TextQuote,
  Wallet,
  Users,
  Volume2,
  Video,
  Wifi,
  type LucideIcon,
} from "lucide-react";

import type { ToolDefinition } from "@/lib/tools";

const icons: Record<ToolDefinition["icon"], LucideIcon> = {
  split: FileStack,
  image: ImageIcon,
  compress: Minimize2,
  convert: ArrowLeftRight,
  qr: QrCode,
  merge: Combine,
  organize: ListOrdered,
  stamp: Stamp,
  hash: Hash,
  pen: PenLine,
  fileWord: FileType,
  crop: Crop,
  droplets: Droplets,
  layers: Layers,
  grid: LayoutGrid,
  eraser: Eraser,
  video: Video,
  music: Music,
  ruler: Ruler,
  calendar: CalendarDays,
  banknote: Banknote,
  home: Home,
  globe: Globe,
  presentation: Presentation,
  lock: Lock,
  scanText: ScanText,
  clapper: Clapperboard,
  text: TextQuote,
  party: PartyPopper,
  users: Users,
  screen: MonitorSmartphone,
  percent: Percent,
  receipt: ReceiptText,
  scale: Scale,
  wallet: Wallet,
  pulse: HeartPulse,
  pill: Pill,
  calheart: CalendarHeart,
  mail: Mail,
  calculator: Calculator,
  volume: Volume2,
  printer: Printer,
  wifi: Wifi,
  brush: Brush,
  scissors: Scissors,
  book: BookOpen,
  tag: Tag,
  markdown: FileCode2,
};

export function ToolIcon({
  icon,
  className,
}: {
  icon: ToolDefinition["icon"];
  className?: string;
}) {
  const Icon = icons[icon];
  return <Icon aria-hidden="true" className={className} strokeWidth={1.8} />;
}
